feedback and steering
AspieCoder1/mk-docs-material-test pull request #4
Opened 2022-03-31 14:05 UTC by xfde

2022-04-01 10:43 UTC, AspieCoder1 requested changes
Please can you change the inline code to bold? Only use inline code for actual code not for emphasis.

2022-04-01 10:43 UTC, AspieCoder1 commented on docs/guides/refining-solutions/steering.md
> +* `match threshold`: Value in the range 0 to 1. Discards all matches with a score below the threshold.
Make bold not inline code

2022-04-02 09:59 UTC, xfde reviewed
Changed parameters text to bold

2022-04-02 17:28 UTC, AspieCoder1 approved these changes
Looks good. Thank you changing the stuff to bold

2022-04-02 17:30 UTC, merged